# Generated by Django 4.1.7 on 2023-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pdp',
            field=models.ImageField(default='./logo_ispm.jpeg', upload_to='profiling_photo'),
        ),
    ]
