# Generated by Django 4.1.7 on 2023-07-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pdp',
        ),
    ]
