# Generated by Django 4.1.7 on 2023-05-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_annotation_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=75)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.annotation')),
            ],
        ),
    ]
