# Generated by Django 4.2 on 2023-05-15 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='like',
            field=models.ManyToManyField(related_name='fan_zone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='unlike',
            field=models.ManyToManyField(related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
