# Generated by Django 4.2 on 2023-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='liker',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
