# Generated by Django 4.2 on 2023-05-23 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0007_disliker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='fan_zone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='unlike',
            field=models.ManyToManyField(blank=True, null=True, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
